update/improve downloaders

diff --git a/src/dbpedia-2016-04/download-dbpedia b/src/dbpedia-2016-04/download-dbpedia
--- a/src/dbpedia-2016-04/download-dbpedia
+++ b/src/dbpedia-2016-04/download-dbpedia
@@ -1,129 +1,144 @@
 #!/bin/bash
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/ext/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/links/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/statistics/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/af/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/als/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/am/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/an/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ar/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/arz/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ast/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/az/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ba/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/bar/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/be/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/bg/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/bn/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/bpy/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/br/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/bs/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/bug/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ca/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ce/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ceb/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ckb/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/cs/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/cv/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/cy/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/da/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/de/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/el/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/en/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/eo/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/es/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/et/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/eu/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/fa/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/fi/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/fo/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/fr/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/fy/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ga/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/gd/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/gl/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/gu/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/he/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/hi/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/hr/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ht/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/hu/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/hy/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ia/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/id/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/io/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/is/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/it/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ja/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/jv/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ka/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/kk/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/kn/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ko/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ku/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ky/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/la/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/lb/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/lmo/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/lt/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/lv/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/mg/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/mk/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ml/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/mn/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/mr/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ms/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/mt/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/my/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/mzn/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/nah/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/nap/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/nds/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ne/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/new/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/nl/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/nn/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/no/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/oc/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/pa/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/pl/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/pms/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/pnb/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/pt/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/qu/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ro/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ru/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sa/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sah/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/scn/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sco/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sh/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/si/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sk/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sl/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sq/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sr/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/su/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sv/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/sw/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ta/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/te/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/tg/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/th/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/tl/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/tr/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/tt/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/uk/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/ur/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/uz/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/vec/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/vi/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/vo/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/wa/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/war/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/yi/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/yo/ &
-wget -c -q -rm -np http://downloads.dbpedia.org/2016-04/core-i18n/zh/ &
+
+if ! which parallel
+then
+  echo "Need to install GNU Parallel" >&2
+  pkcon install parallel || sudo dnf -y install parallel
+fi
+
+timeout 10 parallel --bibtex --will-cite < /dev/null
+
+# Run WGet in parallel; use up to half the number of CPU cores for this. 
+# Abort whenever 2 jobs have failed.
+
+exec parallel --will-cite --halt now,fail=2 -P50% wget -q -c -r -m -np <<END
+http://downloads.dbpedia.org/2016-04/
+http://downloads.dbpedia.org/2016-04/core/
+http://downloads.dbpedia.org/2016-04/ext/
+http://downloads.dbpedia.org/2016-04/links/
+http://downloads.dbpedia.org/2016-04/statistics/
+http://downloads.dbpedia.org/2016-04/core-i18n/af/
+http://downloads.dbpedia.org/2016-04/core-i18n/als/
+http://downloads.dbpedia.org/2016-04/core-i18n/am/
+http://downloads.dbpedia.org/2016-04/core-i18n/an/
+http://downloads.dbpedia.org/2016-04/core-i18n/ar/
+http://downloads.dbpedia.org/2016-04/core-i18n/arz/
+http://downloads.dbpedia.org/2016-04/core-i18n/ast/
+http://downloads.dbpedia.org/2016-04/core-i18n/az/
+http://downloads.dbpedia.org/2016-04/core-i18n/ba/
+http://downloads.dbpedia.org/2016-04/core-i18n/bar/
+http://downloads.dbpedia.org/2016-04/core-i18n/be/
+http://downloads.dbpedia.org/2016-04/core-i18n/bg/
+http://downloads.dbpedia.org/2016-04/core-i18n/bn/
+http://downloads.dbpedia.org/2016-04/core-i18n/bpy/
+http://downloads.dbpedia.org/2016-04/core-i18n/br/
+http://downloads.dbpedia.org/2016-04/core-i18n/bs/
+http://downloads.dbpedia.org/2016-04/core-i18n/bug/
+http://downloads.dbpedia.org/2016-04/core-i18n/ca/
+http://downloads.dbpedia.org/2016-04/core-i18n/ce/
+http://downloads.dbpedia.org/2016-04/core-i18n/ceb/
+http://downloads.dbpedia.org/2016-04/core-i18n/ckb/
+http://downloads.dbpedia.org/2016-04/core-i18n/cs/
+http://downloads.dbpedia.org/2016-04/core-i18n/cv/
+http://downloads.dbpedia.org/2016-04/core-i18n/cy/
+http://downloads.dbpedia.org/2016-04/core-i18n/da/
+http://downloads.dbpedia.org/2016-04/core-i18n/de/
+http://downloads.dbpedia.org/2016-04/core-i18n/el/
+http://downloads.dbpedia.org/2016-04/core-i18n/en/
+http://downloads.dbpedia.org/2016-04/core-i18n/eo/
+http://downloads.dbpedia.org/2016-04/core-i18n/es/
+http://downloads.dbpedia.org/2016-04/core-i18n/et/
+http://downloads.dbpedia.org/2016-04/core-i18n/eu/
+http://downloads.dbpedia.org/2016-04/core-i18n/fa/
+http://downloads.dbpedia.org/2016-04/core-i18n/fi/
+http://downloads.dbpedia.org/2016-04/core-i18n/fo/
+http://downloads.dbpedia.org/2016-04/core-i18n/fr/
+http://downloads.dbpedia.org/2016-04/core-i18n/fy/
+http://downloads.dbpedia.org/2016-04/core-i18n/ga/
+http://downloads.dbpedia.org/2016-04/core-i18n/gd/
+http://downloads.dbpedia.org/2016-04/core-i18n/gl/
+http://downloads.dbpedia.org/2016-04/core-i18n/gu/
+http://downloads.dbpedia.org/2016-04/core-i18n/he/
+http://downloads.dbpedia.org/2016-04/core-i18n/hi/
+http://downloads.dbpedia.org/2016-04/core-i18n/hr/
+http://downloads.dbpedia.org/2016-04/core-i18n/ht/
+http://downloads.dbpedia.org/2016-04/core-i18n/hu/
+http://downloads.dbpedia.org/2016-04/core-i18n/hy/
+http://downloads.dbpedia.org/2016-04/core-i18n/ia/
+http://downloads.dbpedia.org/2016-04/core-i18n/id/
+http://downloads.dbpedia.org/2016-04/core-i18n/io/
+http://downloads.dbpedia.org/2016-04/core-i18n/is/
+http://downloads.dbpedia.org/2016-04/core-i18n/it/
+http://downloads.dbpedia.org/2016-04/core-i18n/ja/
+http://downloads.dbpedia.org/2016-04/core-i18n/jv/
+http://downloads.dbpedia.org/2016-04/core-i18n/ka/
+http://downloads.dbpedia.org/2016-04/core-i18n/kk/
+http://downloads.dbpedia.org/2016-04/core-i18n/kn/
+http://downloads.dbpedia.org/2016-04/core-i18n/ko/
+http://downloads.dbpedia.org/2016-04/core-i18n/ku/
+http://downloads.dbpedia.org/2016-04/core-i18n/ky/
+http://downloads.dbpedia.org/2016-04/core-i18n/la/
+http://downloads.dbpedia.org/2016-04/core-i18n/lb/
+http://downloads.dbpedia.org/2016-04/core-i18n/lmo/
+http://downloads.dbpedia.org/2016-04/core-i18n/lt/
+http://downloads.dbpedia.org/2016-04/core-i18n/lv/
+http://downloads.dbpedia.org/2016-04/core-i18n/mg/
+http://downloads.dbpedia.org/2016-04/core-i18n/mk/
+http://downloads.dbpedia.org/2016-04/core-i18n/ml/
+http://downloads.dbpedia.org/2016-04/core-i18n/mn/
+http://downloads.dbpedia.org/2016-04/core-i18n/mr/
+http://downloads.dbpedia.org/2016-04/core-i18n/ms/
+http://downloads.dbpedia.org/2016-04/core-i18n/mt/
+http://downloads.dbpedia.org/2016-04/core-i18n/my/
+http://downloads.dbpedia.org/2016-04/core-i18n/mzn/
+http://downloads.dbpedia.org/2016-04/core-i18n/nah/
+http://downloads.dbpedia.org/2016-04/core-i18n/nap/
+http://downloads.dbpedia.org/2016-04/core-i18n/nds/
+http://downloads.dbpedia.org/2016-04/core-i18n/ne/
+http://downloads.dbpedia.org/2016-04/core-i18n/new/
+http://downloads.dbpedia.org/2016-04/core-i18n/nl/
+http://downloads.dbpedia.org/2016-04/core-i18n/nn/
+http://downloads.dbpedia.org/2016-04/core-i18n/no/
+http://downloads.dbpedia.org/2016-04/core-i18n/oc/
+http://downloads.dbpedia.org/2016-04/core-i18n/pa/
+http://downloads.dbpedia.org/2016-04/core-i18n/pl/
+http://downloads.dbpedia.org/2016-04/core-i18n/pms/
+http://downloads.dbpedia.org/2016-04/core-i18n/pnb/
+http://downloads.dbpedia.org/2016-04/core-i18n/pt/
+http://downloads.dbpedia.org/2016-04/core-i18n/qu/
+http://downloads.dbpedia.org/2016-04/core-i18n/ro/
+http://downloads.dbpedia.org/2016-04/core-i18n/ru/
+http://downloads.dbpedia.org/2016-04/core-i18n/sa/
+http://downloads.dbpedia.org/2016-04/core-i18n/sah/
+http://downloads.dbpedia.org/2016-04/core-i18n/scn/
+http://downloads.dbpedia.org/2016-04/core-i18n/sco/
+http://downloads.dbpedia.org/2016-04/core-i18n/sh/
+http://downloads.dbpedia.org/2016-04/core-i18n/si/
+http://downloads.dbpedia.org/2016-04/core-i18n/sk/
+http://downloads.dbpedia.org/2016-04/core-i18n/sl/
+http://downloads.dbpedia.org/2016-04/core-i18n/sq/
+http://downloads.dbpedia.org/2016-04/core-i18n/sr/
+http://downloads.dbpedia.org/2016-04/core-i18n/su/
+http://downloads.dbpedia.org/2016-04/core-i18n/sv/
+http://downloads.dbpedia.org/2016-04/core-i18n/sw/
+http://downloads.dbpedia.org/2016-04/core-i18n/ta/
+http://downloads.dbpedia.org/2016-04/core-i18n/te/
+http://downloads.dbpedia.org/2016-04/core-i18n/tg/
+http://downloads.dbpedia.org/2016-04/core-i18n/th/
+http://downloads.dbpedia.org/2016-04/core-i18n/tl/
+http://downloads.dbpedia.org/2016-04/core-i18n/tr/
+http://downloads.dbpedia.org/2016-04/core-i18n/tt/
+http://downloads.dbpedia.org/2016-04/core-i18n/uk/
+http://downloads.dbpedia.org/2016-04/core-i18n/ur/
+http://downloads.dbpedia.org/2016-04/core-i18n/uz/
+http://downloads.dbpedia.org/2016-04/core-i18n/vec/
+http://downloads.dbpedia.org/2016-04/core-i18n/vi/
+http://downloads.dbpedia.org/2016-04/core-i18n/vo/
+http://downloads.dbpedia.org/2016-04/core-i18n/wa/
+http://downloads.dbpedia.org/2016-04/core-i18n/war/
+http://downloads.dbpedia.org/2016-04/core-i18n/yi/
+http://downloads.dbpedia.org/2016-04/core-i18n/yo/
+http://downloads.dbpedia.org/2016-04/core-i18n/zh/
+http://downloads.dbpedia.org/2016-04/core-i18n/
+END
+
