Improve mop-up downloads

diff --git a/src/dbpedia-2016-04/wait-for-checksums b/src/dbpedia-2016-04/wait-for-checksums
--- a/src/dbpedia-2016-04/wait-for-checksums
+++ b/src/dbpedia-2016-04/wait-for-checksums
@@ -1,28 +1,21 @@
 #!/bin/bash
 until ./check-checksums
 do
-  echo "One or more files have not downloaded properly." >&2
-  echo "Assuming that the download processes are still running …"
-  if ! pgrep -af wget | grep dbpedia
-  then
-    echo "It seems that they have stopped. Let's restart them."
-    ./download-dbpedia &
-    sleep 3
-    if ! pgrep -af wget | grep dbpedia
+    echo "So far, downloaded:"
+    du -sh downloads.dbpedia.org
+    echo "Available space on volume:"
+    df -h .
+    echo ""
+    echo "One or more files have not downloaded properly." >&2
+    echo "Are the download processes are still running …?"
+    if pgrep -af wget | grep dbpedia
     then
-      echo "Downloads are not running; aborting" >&2
-      exit 4
+        echo "They are; let's sleep a couple minutes before checking again."
+        sleep 200
+    else
+        echo "It seems that they have stopped, so we'll just fetch any missing bits."
+        ./grab-missing
     fi
-  fi
-  echo "Downloads are running, so we'll wait a few minutes and try again."
-  echo "So far, downloaded:"
-  du -sh downloads.dbpedia.org
-  echo "Available space on volume:"
-  df -h .
-  date
-  echo ""
-  sleep 275
-  date
 done
 echo "All seems well. Done."
 exit 0
